name: Publish package to GitHub Packages

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@FMI-MediaMaster'

      - name: Install pnpm 
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm run build

      - name: Set Tag Name
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/v}
          echo "TAG_NAME=$TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Set package version
        if: startsWith(github.ref, 'refs/tags/')
        run: pnpm version ${{ env.TAG_NAME }} --no-git-tag-version

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/')
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
